"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "./Header.module.css";
import { usePathname, useRouter } from "next/navigation";

// import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const pathname = usePathname();

  const isHomePage = pathname === "/";

  return (
    <html lang="en">
      <head></head>
      <title>Mendoza y Guttierrez</title>
      {/* <meta name="description" content={metadata.description} /> */}
      <link rel="icon" href="/logo.jpeg" />

      <body>
        <nav className="navbar container">
          {!isHomePage && (
            <a onClick={() => router.back()} className="navbar-brand" href="#">
              &larr; Regresar
            </a>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
